// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_apk_kw_ from "./routes/api/apk/[kw].ts";
import * as $api_apk_create from "./routes/api/apk/create.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $patchouli_index from "./routes/patchouli/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Info from "./islands/Info.tsx";
import * as $LemonDrop from "./islands/LemonDrop.tsx";
import * as $Search from "./islands/Search.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/apk/[kw].ts": $api_apk_kw_,
    "./routes/api/apk/create.ts": $api_apk_create,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/patchouli/index.tsx": $patchouli_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Info.tsx": $Info,
    "./islands/LemonDrop.tsx": $LemonDrop,
    "./islands/Search.tsx": $Search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
